name: fhir
on: [push]

# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fhir
    steps:
      - uses: actions/checkout@v4

      - name: Create conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: fhir/environment.yml
          environment-name: raw-fhir
          cache-environment: true

      - name: Install test dependencies
        shell: bash -l {0}
        run: |
          micromamba activate raw-fhir
          pip install -r requirements-dev.txt

      - name: Run lint
        shell: bash -l {0}
        run: |
          micromamba activate raw-fhir
          make lintci

  # test:
  #   name: test
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./api
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Create conda environment
  #       uses: mamba-org/setup-micromamba@v1
  #       with:
  #         environment-file: api/environment.yml
  #         environment-name: raw-fhir
  #         cache-environment: true

  #     - name: Install dev dependencies
  #       shell: bash -l {0}
  #       run: |
  #         micromamba activate raw-fhir
  #         pip install -r requirements-dev.txt
  #         pip install -e .

  #     - name: Run tests
  #       shell: bash -l {0}
  #       run: |
  #         micromamba activate raw-fhir
  #         make test
